import ArticleIcon from "@mui/icons-material/Article";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import EditNoteIcon from "@mui/icons-material/EditNote";
import GraphicEqIcon from "@mui/icons-material/GraphicEq";
import HearingIcon from "@mui/icons-material/Hearing";
import ImageSearchIcon from "@mui/icons-material/ImageSearch";
import LibraryBooksIcon from "@mui/icons-material/LibraryBooks";
import MicIcon from "@mui/icons-material/Mic";
import PsychologyIcon from "@mui/icons-material/Psychology";
import SpellcheckIcon from "@mui/icons-material/Spellcheck";
import SubjectIcon from "@mui/icons-material/Subject";
import TextFieldsIcon from "@mui/icons-material/TextFields";
import TuneIcon from "@mui/icons-material/Tune";

export const pteSections = [
  {
    id: "speaking-writing",
    title: "Speaking & Writing",
    color: "#0f766e",
    description: "Practice speaking with recorder-based drills and use AI scoring where the task needs written evaluation.",
  },
  {
    id: "reading",
    title: "Reading",
    color: "#4338ca",
    description: "Build reading accuracy with reorder, fill blank, and multiple-choice practice formats.",
  },
  {
    id: "listening",
    title: "Listening",
    color: "#be123c",
    description: "Use transcript-based listening practice now, with audio-first practice planned later.",
  },
];

export const pteTasks = [
  {
    slug: "read-aloud",
    section: "speaking-writing",
    title: "Read Aloud",
    shortTitle: "Read Aloud",
    icon: MicIcon,
    textScoring: false,
    status: "guide",
    time: "30-40 sec preparation",
    seoTitle: "Free PTE Read Aloud Practice | A Plus Academy",
    description: "Free PTE Read Aloud practice guide with pronunciation, fluency, and punctuation tips.",
    prepSeconds: 40,
    answerSeconds: 40,
    prompt: "Read the paragraph clearly. Focus on pronunciation, phrasing, and pauses at punctuation.",
    sample:
      "Academic success depends not only on memorising information, but also on developing the ability to explain ideas clearly and apply them to unfamiliar situations.",
    tips: ["Scan punctuation before speaking.", "Group words into meaningful chunks.", "Avoid rushing at the end of the sentence."],
  },
  {
    slug: "repeat-sentence",
    section: "speaking-writing",
    title: "Repeat Sentence",
    shortTitle: "Repeat Sentence",
    icon: HearingIcon,
    textScoring: false,
    status: "guide",
    time: "Listen once, then repeat",
    seoTitle: "Free PTE Repeat Sentence Practice | A Plus Academy",
    description: "Free PTE Repeat Sentence preparation with memory and pronunciation strategies.",
    prepSeconds: 0,
    answerSeconds: 15,
    prompt: "Listen to the sentence, remember the meaning, and repeat it as accurately as possible.",
    sample: "Students who revise regularly are more likely to retain important academic concepts.",
    tips: ["Remember meaning, not only words.", "Repeat the sentence rhythm quickly in your mind.", "Keep speaking even if one word is missed."],
  },
  {
    slug: "describe-image",
    section: "speaking-writing",
    title: "Describe Image",
    shortTitle: "Describe Image",
    icon: ImageSearchIcon,
    textScoring: false,
    status: "guide",
    time: "25 sec preparation",
    seoTitle: "Free PTE Describe Image Practice | A Plus Academy",
    description: "Free PTE Describe Image practice structure for charts, maps, and diagrams.",
    prepSeconds: 25,
    answerSeconds: 40,
    prompt: "Describe the main trend, highest and lowest values, and one important comparison.",
    sample: "A line graph shows a steady rise in online learning between 2018 and 2025, with the fastest growth after 2021.",
    tips: ["Start with the image type.", "Mention one major trend.", "End with a short conclusion."],
  },
  {
    slug: "retell-lecture",
    section: "speaking-writing",
    title: "Retell Lecture",
    shortTitle: "Retell Lecture",
    icon: GraphicEqIcon,
    textScoring: false,
    status: "guide",
    time: "40 sec response",
    seoTitle: "Free PTE Retell Lecture Practice | A Plus Academy",
    description: "Free PTE Retell Lecture practice with note-taking and response structure.",
    prepSeconds: 10,
    answerSeconds: 40,
    prompt: "Retell the lecture by covering the topic, two key points, and the speaker's conclusion.",
    sample: "The lecture explains how urban transport planning reduces congestion, improves air quality, and supports economic productivity.",
    tips: ["Write nouns and numbers while listening.", "Use a fixed opening phrase.", "Connect points with because, however, and therefore."],
  },
  {
    slug: "answer-short-question",
    section: "speaking-writing",
    title: "Answer Short Question",
    shortTitle: "Short Question",
    icon: PsychologyIcon,
    textScoring: false,
    status: "guide",
    time: "Answer immediately",
    seoTitle: "Free PTE Answer Short Question Practice | A Plus Academy",
    description: "Free PTE Answer Short Question practice for common academic vocabulary.",
    prepSeconds: 0,
    answerSeconds: 10,
    prompt: "Give a direct one-word or short-phrase answer.",
    sample: "What device is used to measure temperature? Answer: thermometer.",
    tips: ["Answer directly.", "Do not explain unless required.", "Build common science, campus, and daily-life vocabulary."],
  },
  {
    slug: "respond-to-a-situation",
    section: "speaking-writing",
    title: "Respond to a Situation",
    shortTitle: "Respond to Situation",
    icon: SubjectIcon,
    textScoring: true,
    status: "ai",
    time: "Short spoken-style response",
    seoTitle: "Free PTE Respond to a Situation AI Practice | A Plus Academy",
    description: "Free AI scoring for PTE Respond to a Situation written practice before speaking practice.",
    prompt:
      "Your classmate missed an important lecture and asks you for help. Write what you would say in a polite and helpful response.",
    sample:
      "Of course, I can help you. I took detailed notes during the lecture, so I will share the main points with you and explain the examples that the teacher discussed. You should also check the course portal because the slides may already be uploaded there.",
    tips: ["Use polite language.", "Give a practical solution.", "Keep the response natural and complete."],
    minWords: 25,
    maxWords: 90,
  },
  {
    slug: "summarize-written-text",
    section: "speaking-writing",
    title: "Summarize Written Text",
    shortTitle: "Summarize Text",
    icon: ArticleIcon,
    textScoring: true,
    status: "ai",
    time: "10 minutes",
    seoTitle: "Free PTE Summarize Written Text AI Scoring | A Plus Academy",
    description: "Free PTE Summarize Written Text practice with AI feedback for grammar, content, and sentence control.",
    prompt:
      "Read the passage and summarize it in one sentence between 5 and 75 words.\n\nMany universities now combine classroom teaching with online learning platforms. This blended approach allows students to review lectures, complete quizzes, and access learning material outside class hours. However, it also requires discipline because students must manage their time and avoid distractions while studying online.",
    sample:
      "Blended learning gives university students flexible access to lectures, quizzes, and materials outside class, but it also requires strong time management and discipline to prevent online distractions from reducing academic progress.",
    tips: ["Write one sentence only.", "Include the main idea and key contrast.", "Avoid copying long phrases from the passage."],
    minWords: 5,
    maxWords: 75,
  },
  {
    slug: "write-essay",
    section: "speaking-writing",
    title: "Write Essay",
    shortTitle: "Essay",
    icon: EditNoteIcon,
    textScoring: true,
    status: "full",
    time: "20 minutes",
    seoTitle: "Free PTE Essay Practice with AI Scoring | A Plus Academy",
    description: "Free PTE essay practice with Google login, timer, AI scoring, corrections, and student response examples.",
    prompt: "Write a 200-300 word essay on a common PTE Academic topic.",
    sample: "Use the full essay practice module for timed writing, score details, and response sharing.",
    tips: ["Plan before typing.", "Use 4-5 paragraphs.", "Keep a formal academic tone."],
    to: "/pte/write-essay",
  },
  {
    slug: "reading-writing-fill-blanks",
    section: "reading",
    title: "Reading & Writing: Fill in the Blanks",
    shortTitle: "RW Fill Blanks",
    icon: SpellcheckIcon,
    textScoring: false,
    status: "practice",
    time: "Untimed practice",
    seoTitle: "Free PTE Reading and Writing Fill in the Blanks Practice",
    description: "Free PTE Reading and Writing Fill in the Blanks practice with instant answer checking.",
    prompt:
      "Complete the paragraph using the best words: Digital libraries have made academic resources more ______, allowing students to consult journals and books without being limited by physical ______.",
    sample: "accessible, distance",
    tips: ["Check grammar before meaning.", "Look at collocations.", "Read the complete sentence after filling blanks."],
    minWords: 2,
    maxWords: 20,
  },
  {
    slug: "multiple-choice-multiple-answers",
    section: "reading",
    title: "Multiple Choice, Multiple Answers",
    shortTitle: "Multiple Answers",
    icon: CheckCircleIcon,
    textScoring: false,
    status: "practice",
    time: "Reading practice",
    seoTitle: "Free PTE Reading Multiple Choice Multiple Answers Practice",
    description: "Free PTE Reading Multiple Choice Multiple Answers practice and strategy guide.",
    prompt: "Read the passage carefully and choose all correct answers. Full interactive choices will be added in the next update.",
    sample: "Students should identify facts, opinions, and distractors before choosing multiple answers.",
    tips: ["Wrong choices can reduce marks.", "Select only options supported by the text.", "Avoid choosing based on one familiar word."],
  },
  {
    slug: "reorder-paragraphs",
    section: "reading",
    title: "Re-order Paragraphs",
    shortTitle: "Re-order",
    icon: TuneIcon,
    textScoring: false,
    status: "practice",
    time: "Reading logic practice",
    seoTitle: "Free PTE Re-order Paragraphs Practice",
    description: "Free PTE Re-order Paragraphs practice with order checking.",
    prompt:
      "Write the correct order of these paragraphs as letters only.\nA. Finally, students can review their mistakes and improve their next attempt.\nB. First, they should understand the question and identify the topic.\nC. After that, they can plan the structure before writing the answer.",
    sample: "B C A",
    tips: ["Find the opening sentence first.", "Track pronouns and linking phrases.", "Look for logical time order."],
    minWords: 3,
    maxWords: 10,
  },
  {
    slug: "reading-fill-blanks",
    section: "reading",
    title: "Reading: Fill in the Blanks",
    shortTitle: "Reading Blanks",
    icon: TextFieldsIcon,
    textScoring: false,
    status: "practice",
    time: "Vocabulary practice",
    seoTitle: "Free PTE Reading Fill in the Blanks Practice",
    description: "Free PTE Reading Fill in the Blanks practice with instant answer checking for vocabulary and grammar accuracy.",
    prompt:
      "Complete the sentence: Effective note-taking helps students ______ information, organize ideas, and prepare more efficiently for exams.",
    sample: "retain",
    tips: ["Use grammar clues.", "Think about academic collocations.", "Choose the word that fits the whole sentence."],
    minWords: 1,
    maxWords: 10,
  },
  {
    slug: "reading-multiple-choice-single-answer",
    section: "reading",
    title: "Multiple Choice, Single Answer",
    shortTitle: "Single Answer",
    icon: CheckCircleIcon,
    textScoring: false,
    status: "practice",
    time: "Reading practice",
    seoTitle: "Free PTE Reading Multiple Choice Single Answer Practice",
    description: "Free PTE Reading Multiple Choice Single Answer practice and exam tips.",
    prompt: "Read a passage and select the one best answer. Interactive options will be added in the next update.",
    sample: "Focus on the writer's main purpose instead of isolated words.",
    tips: ["Find the main idea.", "Eliminate extreme options.", "Check whether the answer covers the whole passage."],
  },
  {
    slug: "summarize-spoken-text",
    section: "listening",
    title: "Summarize Spoken Text",
    shortTitle: "Summarize Spoken",
    icon: GraphicEqIcon,
    textScoring: true,
    status: "ai",
    time: "10 minutes",
    seoTitle: "Free PTE Summarize Spoken Text AI Practice",
    description: "Free PTE Summarize Spoken Text practice with AI scoring using transcript-based prompts.",
    prompt:
      "Transcript practice: A lecturer explains that renewable energy is becoming cheaper because technology is improving and production is increasing. However, governments still need to invest in storage systems and modern power grids so that solar and wind energy can be used reliably.\n\nWrite a 50-70 word summary.",
    sample:
      "The lecture explains that renewable energy is becoming more affordable due to technological progress and larger-scale production. However, the speaker emphasizes that governments must still invest in better storage systems and modern electricity grids so that solar and wind power can be supplied reliably.",
    tips: ["Write 50-70 words.", "Include the main topic and two key points.", "Avoid adding your own opinion."],
    minWords: 35,
    maxWords: 90,
  },
  {
    slug: "listening-fill-blanks",
    section: "listening",
    title: "Listening: Fill in the Blanks",
    shortTitle: "Listening Blanks",
    icon: TextFieldsIcon,
    textScoring: false,
    status: "practice",
    time: "Transcript practice",
    seoTitle: "Free PTE Listening Fill in the Blanks Practice",
    description: "Free PTE Listening Fill in the Blanks practice using transcript-based exercises and instant checking.",
    prompt:
      "Transcript practice: Online courses are now ______ in many universities because they provide flexible access to lectures and study ______.",
    sample: "common, materials",
    tips: ["Listen for exact spelling.", "Check singular and plural forms.", "Use grammar around the blank."],
    minWords: 2,
    maxWords: 20,
  },
  {
    slug: "highlight-correct-summary",
    section: "listening",
    title: "Highlight Correct Summary",
    shortTitle: "Correct Summary",
    icon: LibraryBooksIcon,
    textScoring: false,
    status: "practice",
    time: "Listening practice",
    seoTitle: "Free PTE Highlight Correct Summary Practice",
    description: "Free PTE Highlight Correct Summary strategy and practice guide.",
    prompt: "Listen to the recording and choose the summary that best captures the main idea. Interactive choices will be added in the next update.",
    sample: "The correct summary should cover the speaker's central point, not one small detail.",
    tips: ["Ignore options with unsupported details.", "Track the speaker's final message.", "Choose the broadest accurate summary."],
  },
  {
    slug: "select-missing-word",
    section: "listening",
    title: "Select Missing Word",
    shortTitle: "Missing Word",
    icon: HearingIcon,
    textScoring: false,
    status: "practice",
    time: "Listening prediction",
    seoTitle: "Free PTE Select Missing Word Practice",
    description: "Free PTE Select Missing Word practice and listening prediction strategy.",
    prompt: "Listen to the ending of a recording and select the missing word or phrase. Interactive choices will be added later.",
    sample: "Use context and the speaker's direction to predict the ending.",
    tips: ["Do not wait for every word.", "Predict the meaning before the final beep.", "Choose the option that completes the message."],
  },
  {
    slug: "highlight-incorrect-words",
    section: "listening",
    title: "Highlight Incorrect Words",
    shortTitle: "Incorrect Words",
    icon: SpellcheckIcon,
    textScoring: false,
    status: "practice",
    time: "Transcript practice",
    seoTitle: "Free PTE Highlight Incorrect Words Practice",
    description: "Free PTE Highlight Incorrect Words practice with typed correction checking.",
    prompt:
      "Transcript correction: The speaker says 'Students must submit the assignment by Friday', but the text shows 'Students must submit the assessment by Friday'. Type the incorrect word and the correction.",
    sample: "assessment -> assignment",
    tips: ["Focus on meaning-changing words.", "Watch similar-sounding academic words.", "Type the correction clearly."],
    minWords: 2,
    maxWords: 20,
  },
  {
    slug: "write-from-dictation",
    section: "listening",
    title: "Write from Dictation",
    shortTitle: "Dictation",
    icon: EditNoteIcon,
    textScoring: false,
    status: "practice",
    time: "Listen and type",
    seoTitle: "Free PTE Write from Dictation Practice",
    description: "Free PTE Write from Dictation practice with typed answer checking.",
    prompt: "Dictation sentence: Regular feedback helps students improve their academic writing skills.",
    sample: "Regular feedback helps students improve their academic writing skills.",
    tips: ["Type every word.", "Check plural endings.", "Use sentence grammar to recover missed words."],
    minWords: 5,
    maxWords: 25,
  },
];

export const textScoredTasks = pteTasks.filter((task) => task.textScoring);

export const getPteTask = (slug) => pteTasks.find((task) => task.slug === slug);

export const getSectionTasks = (sectionId) => pteTasks.filter((task) => task.section === sectionId);
