export const languageCourses = [
  {
    slug: "english",
    name: "English Language",
    shortName: "English",
    flagCode: "gb",
    countryLabel: "United Kingdom",
    tag: "Spoken English, writing, grammar",
    priceFrom: 8500,
    duration: "8 to 12 weeks",
    examTrack: "General English, IELTS, PTE support",
    levelLabel: "Beginner to advanced",
    framework: "CEFR-style progression from basic to confident communication",
    heroTitle: "English Language Course",
    heroIntro:
      "Build stronger speaking, grammar, writing, vocabulary, and real-life communication skills from home through guided live classes.",
    seoDescription:
      "Join English language classes from home with speaking, grammar, writing, vocabulary, and exam-focused support for learners in Pakistan.",
    gradient: "linear-gradient(135deg, #1d4ed8, #dc2626)",
    surfaceTint: "#eff6ff",
    accentColor: "#1d4ed8",
    focusPoints: ["Speaking confidence", "Grammar correction", "Writing practice", "Presentation skills"],
    detailedOverview:
      "This English language course is designed for learners who need stronger spoken communication, grammar control, academic writing, reading fluency, and vocabulary growth. The course can be shaped for school support, university readiness, interview preparation, business communication, or international English testing foundations.",
    classFormat: [
      "Live guided classes from home with level-based planning and teacher feedback",
      "Practice across speaking, listening, reading, writing, vocabulary, and grammar correction",
      "Short revision tasks, weekly progress checkpoints, and optional exam-focused direction",
    ],
    modules: [
      "Daily-use vocabulary, sentence formation, and pronunciation support",
      "Grammar basics, speaking routines, reading fluency, and paragraph writing",
      "Interview, presentation, and academic English support for study or career growth",
    ],
    curriculum: [
      "Foundation level work on sentence structure, tenses, articles, prepositions, pronunciation, and common speaking mistakes",
      "Intermediate development in conversation flow, paragraph writing, reading comprehension, listening response, and practical vocabulary use",
      "Advanced support for presentations, academic writing, formal communication, discussion building, and exam-style written responses",
      "Optional test-oriented preparation for learners moving toward IELTS or PTE practice with structure, timing, and language correction",
    ],
    supportFeatures: [
      "Speaking correction with attention to fluency, clarity, and confidence",
      "Grammar repair with teacher explanation instead of only memorized rules",
      "Writing review for emails, assignments, summaries, and formal responses",
      "Practical vocabulary building for study, work, travel, and interview settings",
    ],
    outcomes: [
      "Speak more confidently in class, work, and interview settings",
      "Write cleaner sentences, messages, and short assignments",
      "Prepare for IELTS or PTE foundations with better language control",
    ],
    audience: ["School and college students", "University learners", "Job seekers", "Adults improving spoken English"],
    idealFor: [
      "Learners who feel shy while speaking English",
      "Students who understand English but make frequent grammar mistakes",
      "Working adults who need better communication for interviews and office use",
      "Students planning IELTS or PTE preparation after building core language control",
    ],
    packages: [
      {
        name: "English + PTE Starter",
        price: 15000,
        period: "per month",
        description: "Foundation support for grammar, writing structure, vocabulary growth, and guided PTE readiness.",
        highlights: ["2 to 3 guided classes weekly", "English correction and PTE basics", "Best for early-stage learners"],
      },
      {
        name: "English + PTE Advanced",
        price: 20000,
        period: "per month",
        description: "Stronger practice for writing, reading, speaking confidence, and regular PTE-oriented improvement tasks.",
        highlights: ["More structured weekly practice", "Closer feedback on language mistakes", "Suitable for active exam preparation"],
      },
      {
        name: "Top Level Instructor",
        price: 30000,
        period: "per month",
        description: "Premium English and PTE support with higher-level instruction, planning, and focused performance guidance.",
        highlights: ["Top instructor support", "Sharper exam strategy and correction", "Useful for serious score improvement goals"],
      },
    ],
    relatedPathways: [
      { label: "Free PTE Practice", to: "/pte", note: "Move from English foundations into PTE writing and text-based practice." },
    ],
  },
  {
    slug: "german",
    name: "German Language",
    shortName: "German",
    flagCode: "de",
    countryLabel: "Germany",
    tag: "CEFR levels and Goethe-style preparation",
    priceFrom: 12000,
    duration: "10 to 14 weeks",
    examTrack: "A1 to B2, Goethe-oriented preparation",
    levelLabel: "A1 to B2",
    framework: "CEFR-aligned learning path with listening, speaking, reading, and writing",
    heroTitle: "German Language Course",
    heroIntro:
      "Learn German from home with a structured A1 to B2 pathway, guided speaking practice, grammar work, and exam-focused preparation.",
    seoDescription:
      "German language course in Pakistan with online A1 to B2 classes, Goethe-style preparation, speaking practice, and fees from Rs. 12,000.",
    seoTitle: "German Language Course in Pakistan | Online Classes & Fees",
    gradient: "linear-gradient(135deg, #111827, #b91c1c, #f59e0b)",
    surfaceTint: "#fff7ed",
    accentColor: "#b91c1c",
    focusPoints: ["CEFR progression", "Conversation practice", "Grammar and writing", "Goethe exam support"],
    detailedOverview:
      "This German course follows a practical level-based structure for learners targeting study, migration, work, or general language growth. The focus stays on CEFR-style progress with conversation practice, grammar control, reading improvement, listening work, and exam-oriented preparation where needed.",
    classFormat: [
      "Structured online lessons from beginner to upper-intermediate stages",
      "Balanced work across speaking, listening, reading, writing, and grammar",
      "Revision support with level checkpoints for A1, A2, B1, and B2 goals",
    ],
    modules: [
      "A1 and A2 beginner lessons with introductions, daily conversation, and basic sentence structure",
      "B1 and B2 progression with reading comprehension, written responses, and stronger listening practice",
      "Exam-style practice for common Goethe-related goals and practical language use",
    ],
    curriculum: [
      "Beginner German with greetings, introductions, articles, verb placement, sentence building, and everyday communication",
      "Intermediate skill-building in grammar accuracy, listening comprehension, writing short messages, and reading practical texts",
      "Higher-level practice for opinions, structured responses, study-related communication, and more natural conversation flow",
      "Goethe-style direction for learners working toward formal exams or German-speaking study routes",
    ],
    supportFeatures: [
      "CEFR-style progression planning instead of random topic teaching",
      "Speaking practice for travel, study, and formal introduction situations",
      "Grammar explanations with correction on sentence structure and word order",
      "Reading and writing tasks aligned with real learner goals",
    ],
    outcomes: [
      "Handle introductions, travel, study, and basic workplace conversation",
      "Read short texts and write structured messages with better grammar accuracy",
      "Prepare for German study or migration pathways with a clear level roadmap",
    ],
    audience: ["Study abroad learners", "Migration-focused students", "Professionals", "Beginners starting from zero"],
    idealFor: [
      "Students planning Germany-related admissions",
      "Learners targeting migration or embassy language requirements",
      "Professionals needing basic workplace or relocation communication",
      "Beginners who want a proper A1 to B2 roadmap",
    ],
    seoContent: {
      heading: "German language course in Pakistan: a practical A1 to B2 roadmap",
      paragraphs: [
        "A German language course in Pakistan should give a learner a clear route from the first greeting to confident, level-appropriate communication. Many students begin because they are considering study, work, family relocation, or a future Germany-related application. The useful first step is not rushing into difficult exam material. It is building the A1 foundation carefully: pronunciation, everyday vocabulary, articles, personal introductions, common verbs, sentence order, numbers, dates, and the language needed for routine situations. A structured online class gives learners a place to ask questions, practise aloud, and correct small errors before they become habits.",
        "For learners asking how to learn German language in Pakistan, consistency matters more than trying to memorise large word lists in one weekend. Classes should combine a short explanation, guided examples, listening practice, speaking turns, controlled writing, and revision from previous lessons. A learner may start with simple tasks such as introducing family members, booking an appointment, describing a routine, or asking for directions. As confidence grows, A2 and B1 work can introduce longer conversations, practical reading, short emails, opinions, and more accurate grammar. This gradual progression helps learners understand what each CEFR level means in everyday use.",
        "German language course fees in Lahore and elsewhere in Pakistan can vary according to class size, teacher experience, frequency, the learner's current level, and whether the course includes one-to-one attention. This course starts from Rs. 12,000, while a final monthly plan should be agreed after discussing the target level and schedule. Before joining, students should ask how many live sessions are included, whether feedback is provided on writing and speaking, what revision material is used, and whether the teacher can plan toward a specific A1, A2, B1, or B2 goal. Clear answers make comparing courses much easier.",
        "Goethe-style preparation is most effective after the learner has built the language skills an exam expects. Instead of teaching only sample answers, classes should develop reading, listening, writing, and speaking together. Learners can practise short messages, comprehension tasks, formal and informal expressions, and spoken responses with teacher feedback. A good teacher explains why a sentence needs a particular word order or article, then gives the learner enough opportunities to use it naturally. That approach is more durable than memorising a script and is useful even when a learner's exam date changes.",
        "Online German classes are a practical option for learners in Lahore, Karachi, Islamabad, Faisalabad, Multan, and other parts of Pakistan because the course can fit around school, university, or work. Learners still need a quiet place, regular attendance, a notebook or digital document for corrections, and time between classes for review. The aim is not simply to complete lessons; it is to move from recognising German to using it with clarity. Students who track their vocabulary, keep corrected writing samples, and revisit weak grammar points generally make more dependable progress from one level to the next.",
      ],
    },
    seoFaqs: [
      ["What is included in a German language course in Pakistan?", "A structured course should cover speaking, listening, reading, writing, vocabulary, grammar, revision, and level-based feedback. The exact plan depends on the learner's A1 to B2 target."],
      ["How much does a German language course cost?", "This course starts from Rs. 12,000. The final fee depends on the class format, weekly schedule, learner level, and amount of individual teacher support required."],
      ["Can beginners learn German online from Pakistan?", "Yes. Beginners can start online with pronunciation, basic vocabulary, sentence building, listening, and guided speaking practice, provided they follow a regular study routine."],
      ["Does the course support Goethe exam preparation?", "The course can provide Goethe-style practice after the learner has built the required language foundation for the relevant level."],
    ],
  },
  {
    slug: "chinese",
    name: "Chinese Language",
    shortName: "Chinese",
    flagCode: "cn",
    countryLabel: "China",
    tag: "Pinyin, tones, characters, HSK pathway",
    priceFrom: 12500,
    duration: "10 to 14 weeks",
    examTrack: "HSK beginner to intermediate pathway",
    levelLabel: "Starter to HSK 4",
    framework: "Pinyin, tone control, vocabulary, characters, and conversation practice",
    heroTitle: "Chinese Language Course",
    heroIntro:
      "Start learning Chinese from home with pinyin, pronunciation, tones, practical conversation, and a gradual HSK-oriented study track.",
    seoDescription:
      "Chinese language course in Pakistan with online pinyin, tones, characters, speaking practice, and HSK-based progression for beginners.",
    seoTitle: "Chinese Language Course in Pakistan | Learn Chinese Online",
    gradient: "linear-gradient(135deg, #991b1b, #f59e0b)",
    surfaceTint: "#fff7ed",
    accentColor: "#b45309",
    focusPoints: ["Pinyin and tones", "Basic conversation", "Character recognition", "HSK support"],
    detailedOverview:
      "This Chinese language course gives beginners and early intermediate learners a structured path through pinyin, tones, common vocabulary, character familiarity, listening practice, and practical spoken Chinese. It can also be shaped for learners moving toward HSK-based progress.",
    classFormat: [
      "Live home-based classes with tone practice, repetition drills, and teacher correction",
      "Step-by-step movement from pinyin and basic speaking into character recognition and reading confidence",
      "Practice for everyday communication, study planning, or business-oriented language foundations",
    ],
    modules: [
      "Pinyin, tones, greetings, numbers, and basic sentence patterns",
      "Everyday vocabulary, listening drills, reading practice, and character familiarity",
      "HSK-style preparation for learners targeting study, travel, or work-related communication",
    ],
    curriculum: [
      "Starter work on pinyin, tones, pronunciation control, greetings, self-introduction, and basic sentence order",
      "Vocabulary expansion through daily themes such as numbers, time, family, travel, shopping, and classroom language",
      "Listening and reading practice using short guided texts with introductory character exposure",
      "HSK-style pathway building for learners who may later sit formal Chinese language tests",
    ],
    supportFeatures: [
      "Tone correction for clearer pronunciation from the beginning",
      "Speaking support for practical day-to-day conversations",
      "Character recognition strategies for beginners who feel overwhelmed",
      "Progressive vocabulary reinforcement through repetition and teacher feedback",
    ],
    outcomes: [
      "Pronounce common sounds more accurately and understand basic conversation",
      "Recognize useful vocabulary and introductory characters",
      "Build a foundation for HSK-based progress and future study goals",
    ],
    audience: ["Students interested in business or study links", "Beginners", "Travel learners", "Professionals expanding language skills"],
    idealFor: [
      "Students planning Chinese language foundations for future academic routes",
      "Business-minded learners interested in China-related communication",
      "Beginners starting from zero",
      "Learners who want a guided path instead of only app-based self-study",
    ],
    seoContent: {
      heading: "Chinese language course in Pakistan for practical learning and HSK progress",
      paragraphs: [
        "A Chinese language course in Pakistan works best when it starts with the foundations learners need before they face long vocabulary lists or complex characters. For most beginners, this means pinyin, tone awareness, sound practice, greetings, numbers, self-introduction, and basic sentence patterns. Mandarin tones can change meaning, so teacher correction early in the course is valuable. Learners do not need to become perfect on the first day, but they should learn to hear, repeat, and compare sounds with care. That confidence makes later speaking and listening practice much more comfortable.",
        "Students searching for Chinese language classes in Pakistan often have different goals. Some are preparing for future study, some are interested in business communication, and others want a serious language skill alongside university or work. The course can begin with useful daily themes such as time, family, travel, food, shopping, directions, and classroom language. Rather than treating vocabulary as a random list, each lesson should show how words appear in short conversations, questions, and written examples. Repeated use helps learners recall the language when they need it instead of only recognising it in a book.",
        "For a learner looking to learn Chinese in Karachi or any other Pakistani city, online classes make it possible to work with a teacher without travelling across the city. A successful remote course still needs active participation. Learners should speak during class, complete small listening exercises, write pinyin or characters by hand where helpful, and review corrections between sessions. Short, steady practice is particularly useful for tones and character familiarity. A teacher can then adapt lessons to problems that appear in real time, such as confusing similar sounds or forgetting word order.",
        "Character learning should be gradual and meaningful. At beginner level, the priority is recognising high-frequency characters connected to the vocabulary already being used in conversation. Learners can study the components of characters, practise short words and labels, and read controlled sentences rather than trying to memorise hundreds of disconnected symbols. Pinyin remains helpful in the early stages, but the long-term aim is to reduce reliance on it step by step. This approach gives students a more realistic route to reading confidence and avoids making the writing system feel unmanageable.",
        "An HSK-oriented pathway can help learners organise their progress, but a strong course does not reduce learning to a test. Listening, speaking, reading, writing, vocabulary, and pronunciation should support each other. Before enrolling, learners should discuss their starting point, purpose, available study time, preferred schedule, and any examination plan. This course starts from Rs. 12,500 and can be adjusted for beginner or early-intermediate needs. With regular feedback and sensible weekly goals, a Chinese course can become a practical foundation for future study, work, travel, or formal HSK preparation.",
      ],
    },
    seoFaqs: [
      ["Can I learn Chinese online from Pakistan?", "Yes. Online Chinese classes can cover pinyin, tones, vocabulary, conversation, character recognition, reading, and HSK-oriented progress with live teacher feedback."],
      ["What should a beginner learn first in Chinese?", "A beginner should start with pinyin, tones, pronunciation, everyday vocabulary, simple sentence patterns, and guided speaking before taking on more character work."],
      ["Does the Chinese course include HSK preparation?", "The course can follow an HSK-oriented progression and introduce suitable practice as the learner develops the required foundation."],
      ["Who can join Chinese language classes?", "The course is suitable for beginners, students planning future study, professionals, travel learners, and people who want a structured alternative to self-study alone."],
    ],
  },
  {
    slug: "korean",
    name: "Korean Language",
    shortName: "Korean",
    flagCode: "kr",
    countryLabel: "South Korea",
    tag: "Hangul, conversation, TOPIK pathway",
    priceFrom: 12000,
    duration: "10 to 14 weeks",
    examTrack: "TOPIK I and TOPIK II foundation support",
    levelLabel: "Beginner to intermediate",
    framework: "Hangul, sentence patterns, listening, reading, speaking, and TOPIK-style progress",
    heroTitle: "Korean Language Course",
    heroIntro:
      "Learn Korean from home with Hangul basics, structured conversation practice, grammar development, and a clear TOPIK-aligned direction.",
    seoDescription:
      "Join Korean language classes from home with Hangul, speaking practice, reading, writing, listening, and TOPIK-based preparation.",
    gradient: "linear-gradient(135deg, #1d4ed8, #ec4899)",
    surfaceTint: "#fdf2f8",
    accentColor: "#db2777",
    focusPoints: ["Hangul reading", "Conversation practice", "Grammar structure", "TOPIK preparation"],
    detailedOverview:
      "This Korean language course is suitable for learners who want to build strong Hangul reading, practical conversation, beginner to intermediate grammar, and a future pathway toward TOPIK-style preparation. It is designed for consistent skill growth instead of entertainment-only exposure.",
    classFormat: [
      "Live online Korean lessons with reading, listening, speaking, and writing practice",
      "Step-based progress from Hangul basics into sentence patterns and conversational use",
      "Teacher-guided correction for pronunciation, structure, and written answers",
    ],
    modules: [
      "Hangul reading and writing, greetings, sentence patterns, and daily-use expressions",
      "Listening, reading, and short writing practice with gradual grammar expansion",
      "TOPIK-style study direction for learners planning higher-level progression",
    ],
    curriculum: [
      "Hangul recognition, writing, pronunciation, greetings, and beginner self-expression",
      "Grammar and vocabulary building for daily routines, classroom language, preferences, and common interactions",
      "Listening and reading development using short passages, guided comprehension, and controlled speaking tasks",
      "TOPIK-linked progression planning for learners targeting future academic or exam goals",
    ],
    supportFeatures: [
      "Clear support for learners starting with no Hangul knowledge",
      "Conversation building with practical day-to-day Korean",
      "Grammar explanation beyond memorized phrases",
      "Writing and reading tasks to strengthen full-language control",
    ],
    outcomes: [
      "Read Hangul with confidence and speak in common day-to-day situations",
      "Understand beginner to intermediate grammar patterns more clearly",
      "Build a stronger base for TOPIK exams or Korean study goals",
    ],
    audience: ["Students planning Korean study routes", "K-culture learners", "Beginners", "Exam-focused learners"],
    idealFor: [
      "Learners planning Korean study or scholarship paths",
      "Students interested in TOPIK progression later",
      "Beginners who want teacher-led grammar and reading support",
      "Learners who need more than self-paced entertainment content",
    ],
  },
  {
    slug: "japanese",
    name: "Japanese Language",
    shortName: "Japanese",
    flagCode: "jp",
    countryLabel: "Japan",
    tag: "Kana, conversation, JLPT pathway",
    priceFrom: 12500,
    duration: "10 to 14 weeks",
    examTrack: "JLPT N5 to N2 pathway support",
    levelLabel: "Beginner to upper-intermediate",
    framework: "Hiragana, katakana, vocabulary, grammar, conversation, and JLPT-oriented progress",
    heroTitle: "Japanese Language Course",
    heroIntro:
      "Study Japanese from home with hiragana, katakana, core grammar, conversation drills, and a structured JLPT-focused learning path.",
    seoDescription:
      "Learn Japanese online from home with hiragana, katakana, grammar, speaking, vocabulary, and JLPT-based progression.",
    gradient: "linear-gradient(135deg, #f8fafc, #ef4444)",
    surfaceTint: "#fef2f2",
    accentColor: "#dc2626",
    focusPoints: ["Kana mastery", "Conversation drills", "Grammar progression", "JLPT preparation"],
    detailedOverview:
      "This Japanese language course builds a solid path from hiragana and katakana into grammar, practical vocabulary, conversation, reading development, and JLPT-oriented growth. The structure is useful for learners planning study, work, cultural interest, or future certification goals.",
    classFormat: [
      "Live Japanese classes from home with script learning, grammar guidance, and conversation practice",
      "Gradual progress from beginner script recognition into real sentence use and reading confidence",
      "Teacher feedback on pronunciation, grammar patterns, and written work",
    ],
    modules: [
      "Hiragana, katakana, daily introductions, and beginner sentence patterns",
      "Vocabulary growth, listening, reading practice, and early kanji exposure",
      "JLPT-style preparation for learners aiming at N5, N4, N3, or beyond",
    ],
    curriculum: [
      "Hiragana and katakana learning with guided reading practice and pronunciation support",
      "Core beginner grammar, greetings, daily-use expressions, self-introduction, and common sentence forms",
      "Vocabulary growth with listening and reading tasks plus controlled exposure to early kanji",
      "JLPT-oriented progression for learners planning N5, N4, or later-stage study goals",
    ],
    supportFeatures: [
      "Script learning support for learners overwhelmed by kana at the start",
      "Grammar explanation for practical communication instead of phrase memorization only",
      "Listening and reading activities to support balanced development",
      "Structured route toward JLPT-style familiarity",
    ],
    outcomes: [
      "Read kana smoothly and communicate in common beginner situations",
      "Understand practical grammar and vocabulary for study and conversation",
      "Prepare for JLPT progression with clearer structure and practice routines",
    ],
    audience: ["Beginners", "Study abroad learners", "Anime and culture learners", "JLPT-focused students"],
    idealFor: [
      "Beginners starting with no script knowledge",
      "Learners targeting future Japanese study routes",
      "Students who want a proper JLPT-aligned foundation",
      "Culture learners who also want real grammar and reading ability",
    ],
  },
  {
    slug: "arabic",
    name: "Arabic Language",
    shortName: "Arabic",
    flagCode: "sa",
    countryLabel: "Arabic-speaking region",
    tag: "MSA basics, reading, writing, conversation",
    priceFrom: 9000,
    duration: "8 to 12 weeks",
    examTrack: "Modern Standard Arabic foundation",
    levelLabel: "Beginner to intermediate",
    framework: "Alphabet, pronunciation, grammar, reading, writing, and Modern Standard Arabic communication",
    heroTitle: "Arabic Language Course",
    heroIntro:
      "Learn Arabic from home with alphabet mastery, reading, writing, grammar, and practical Modern Standard Arabic communication.",
    seoDescription:
      "Study Arabic online from home with alphabet learning, pronunciation, grammar, reading, writing, and Modern Standard Arabic support.",
    gradient: "linear-gradient(135deg, #065f46, #d97706)",
    surfaceTint: "#ecfdf5",
    accentColor: "#047857",
    focusPoints: ["Arabic alphabet", "Reading and writing", "Grammar basics", "MSA communication"],
    detailedOverview:
      "This Arabic language course gives learners a practical start in alphabet recognition, pronunciation, reading, writing, grammar basics, and Modern Standard Arabic communication. It suits students who want formal language foundations rather than only memorized phrases.",
    classFormat: [
      "Live online classes from home with script work, grammar guidance, and teacher correction",
      "Balanced learning across reading, writing, listening, speaking, and vocabulary themes",
      "Useful for school support, personal learning, formal Arabic foundations, and longer-term progression",
    ],
    modules: [
      "Alphabet, sound recognition, word reading, and introductory sentence building",
      "Grammar basics, vocabulary themes, reading practice, and guided writing tasks",
      "Modern Standard Arabic use for learners interested in communication, study, or broader Arabic understanding",
    ],
    curriculum: [
      "Arabic alphabet mastery with sound recognition, joining forms, word reading, and pronunciation clarity",
      "Basic grammar, sentence building, useful vocabulary themes, and controlled writing support",
      "Reading and listening practice with simple passages, guided comprehension, and structured repetition",
      "Modern Standard Arabic foundations for learners who want a formal and transferable Arabic base",
    ],
    supportFeatures: [
      "Letter-by-letter reading support for learners new to Arabic script",
      "Structured writing practice with teacher correction",
      "Grammar guidance for clearer sentence construction",
      "Formal Arabic orientation suitable for future academic or language growth",
    ],
    outcomes: [
      "Read the Arabic script with better fluency and confidence",
      "Write short phrases and understand basic grammar patterns",
      "Build a solid base for further Arabic study or related academic goals",
    ],
    audience: ["Beginners", "Students of language and culture", "Adults learning from home", "Learners seeking formal Arabic foundations"],
    idealFor: [
      "Learners who want proper Arabic script and reading foundations",
      "Students interested in formal Modern Standard Arabic",
      "Adults learning from home with guided teaching",
      "Beginners who need grammar and writing support from the start",
    ],
  },
];

export const languageCourseMap = Object.fromEntries(
  languageCourses.map((course) => [course.slug, course]),
);
